//! Core traits implemented by native schema types.
//!
//! `#[derive(ConvexDocument)]` generates the impls in this module for
//! developer-defined structs. Each trait is intentionally tiny so the
//! generated code stays readable: the derive macro emits one trait impl per
//! concept (identity, fields, indexes, patch shape).

use common::schemas::TableDefinition;
use value::{
    ConvexObject,
    ConvexValue,
    TableName,
};

/// A Rust struct that corresponds to a Convex table row.
///
/// Implementors are typically generated by `#[derive(ConvexDocument)]`.
/// The implementation must round-trip through [`ConvexObject`] without loss
/// for valid values.
pub trait ConvexDocument: Sized + Clone + Send + Sync + 'static {
    /// Enum of field references for this document (used for typed index keys).
    type Field: FieldReference;
    /// Enum of defined indexes for this document.
    type Index: IndexReference;
    /// Patch type — the same shape with every field wrapped in `Option`.
    type Patch: Default + Clone + Send + Sync + 'static;

    /// The table name this document belongs to.
    fn table_name() -> TableName;

    /// Schema/index declarations for the table (used by `NativeSchema`).
    fn table_definition() -> TableDefinition;

    /// Serialize the document body into a `ConvexObject` (no `_id` field).
    fn to_convex_object(&self) -> anyhow::Result<ConvexObject>;

    /// Parse a document body from a `ConvexObject`.
    fn from_convex_object(obj: ConvexObject) -> anyhow::Result<Self>;
}

/// A typed reference to a field on a [`ConvexDocument`].
///
/// Generated by the derive macro as `XxxField` with one variant per field.
/// Each variant knows its string name — used when building typed index
/// lookups and when translating to the internal `FieldPath` representation.
pub trait FieldReference: Copy + Clone + Send + Sync + 'static {
    /// Dot-separated field name (e.g. `"email"` or `"profile.name"`).
    fn as_str(&self) -> &'static str;
}

/// A typed reference to an index on a [`ConvexDocument`].
///
/// Generated by the derive macro as `XxxIndex` with one variant per
/// `#[convex(index(...))]` attribute.
pub trait IndexReference: Copy + Clone + Send + Sync + 'static {
    /// Index descriptor string (e.g. `"by_email"`).
    fn as_str(&self) -> &'static str;
    /// The field names indexed, in order.
    fn fields(&self) -> &'static [&'static str];
}

/// A partial update to a [`ConvexDocument`].
///
/// The derive macro generates a `XxxPatch` struct with all fields wrapped in
/// `Option`. `to_convex_object` emits only the set fields.
pub trait ConvexPatch: Default + Clone + Send + Sync + 'static {
    type Document: ConvexDocument;

    /// Serialize the set fields into a `ConvexObject` suitable for
    /// `UserFacingModel::patch`.
    fn to_convex_object(&self) -> anyhow::Result<ConvexObject>;
}

/// Helper used by generated code to coerce a `ConvexValue::Object` into a
/// typed document.
pub fn document_from_value<D: ConvexDocument>(v: ConvexValue) -> anyhow::Result<D> {
    let obj = ConvexObject::try_from(v)?;
    D::from_convex_object(obj)
}
