//! Tests the typed ZST marker + args struct generated by
//! `#[convex::query]` / `#[convex::mutation]` / `#[convex::action]`.

use convex_native::{
    convex,
    ctx::action::ActionCtx,
    ConvexActionFunction,
    ConvexDocument,
    ConvexMutationFunction,
    ConvexQueryFunction,
    MutationCtx,
    QueryCtx,
    Rt,
    ToConvex,
};

#[derive(ConvexDocument, Debug, Clone, PartialEq)]
#[convex(table = "beans")]
pub struct Bean {
    pub color: String,
}

#[convex::query]
pub async fn count_beans(_ctx: &mut QueryCtx<'_, Rt>, color: String) -> anyhow::Result<i64> {
    let _ = color;
    Ok(7)
}

#[convex::mutation]
pub async fn stash_bean(
    _ctx: &mut MutationCtx<'_, Rt>,
    color: String,
    weight: f64,
) -> anyhow::Result<()> {
    let _ = (color, weight);
    Ok(())
}

#[convex::action]
pub async fn email_count(_ctx: &mut ActionCtx<'_, Rt>, to: String) -> anyhow::Result<bool> {
    let _ = to;
    Ok(true)
}

#[test]
fn query_marker_trait_matches_registered_name() {
    assert_eq!(<CountBeans as ConvexQueryFunction>::name(), "count_beans");
    // Compile-time checks the associated types — if these don't line up
    // the test won't compile.
    fn _check<Q: ConvexQueryFunction<Args = CountBeansArgs, Output = i64>>() {}
    _check::<CountBeans>();
}

#[test]
fn mutation_marker_trait_matches_registered_name() {
    assert_eq!(<StashBean as ConvexMutationFunction>::name(), "stash_bean");
    fn _check<M: ConvexMutationFunction<Args = StashBeanArgs, Output = ()>>() {}
    _check::<StashBean>();
}

#[test]
fn action_marker_trait_matches_registered_name() {
    assert_eq!(<EmailCount as ConvexActionFunction>::name(), "email_count");
    fn _check<A: ConvexActionFunction<Args = EmailCountArgs, Output = bool>>() {}
    _check::<EmailCount>();
}

#[test]
fn args_struct_round_trips_through_convex_value() {
    use convex_native::FromConvex;
    let args = StashBeanArgs {
        color: "black".into(),
        weight: 1.5,
    };
    let cv = args.clone().to_convex().unwrap();
    let back = StashBeanArgs::from_convex(cv).unwrap();
    assert_eq!(back.color, args.color);
    // float comparison is fine — no arithmetic in between.
    assert_eq!(back.weight, args.weight);
}

#[tokio::test]
async fn typed_action_sub_call_executes_end_to_end() {
    use std::sync::Arc;

    use convex_native::NativeFunctionRunner;

    let runner = Arc::new(NativeFunctionRunner::from_inventory().expect("from_inventory"));

    // Dispatch the registered action directly — we don't have a real
    // ActionCtx orchestrator, but the `run_action` helper on the runner
    // mirrors what `ActionCtx::run_action` does internally.
    let cv = runner
        .run_action(
            <EmailCount as ConvexActionFunction>::name(),
            value::TableNamespace::Global,
            convex_native::ToConvex::to_convex(EmailCountArgs {
                to: "dana@example".into(),
            })
            .unwrap()
            .try_into()
            .unwrap(),
        )
        .await
        .unwrap();

    use convex_native::FromConvex;
    let got: bool = bool::from_convex(cv).unwrap();
    assert!(got);
}
