//! Actions — side-effectful handlers. Actions can sub-call
//! queries / mutations, schedule future work, and touch
//! storage. They don't own a transaction themselves.

use convex_native::{
    convex,
    prelude::*,
    ActionCtx,
    Rt,
};

use crate::{
    queries::{
        GetByEmail,
        GetByEmailArgs,
    },
    schema::User,
};

/// Welcome flow — sub-calls the `by-email` lookup to fetch the
/// user, then `ctx.log()`s a pretend welcome. Demonstrates:
///
/// - Typed action sub-calls (`ctx.run_query(Marker, Args)`).
/// - `ctx.db().get(id)` — snapshot-pinned read on the action ctx.
/// - `ctx.log()` — drained into `UdfOutcome::log_lines` /
///   `ExecuteResponse::log_lines`.
#[convex::action]
pub async fn send_welcome(
    ctx: &mut ActionCtx<'_, Rt>,
    user_id: Id<User>,
) -> anyhow::Result<()> {
    // Direct snapshot read — the action's ctx.db() pins every
    // read to the same ts.
    let Some(user) = ctx.db().get(user_id).await? else {
        ctx.log()
            .warn(format!("send_welcome: user {user_id} not found"));
        return Ok(());
    };
    ctx.log()
        .info(format!("welcome to {}!", user.profile.display_name));

    // Cross-check: the `get_by_email` query must return the same
    // doc. Demonstrates typed sub-calls — the `GetByEmail` marker
    // + `GetByEmailArgs` struct are generated by `#[convex::query]`.
    let by_email = ctx
        .run_query(
            GetByEmail,
            GetByEmailArgs {
                email: user.email.clone(),
            },
        )
        .await?;
    debug_assert!(by_email.is_some());

    // External I/O goes here in a real app (reqwest to an email
    // provider, Stripe, etc.).
    Ok(())
}

/// Internal-only cleanup routine — invoked by the daily cron.
/// `#[convex::action(internal)]` flags the registration so
/// external clients get "function not found"; cron / scheduler
/// callers still reach it.
#[convex::action(internal)]
pub async fn nightly_cleanup(ctx: &mut ActionCtx<'_, Rt>) -> anyhow::Result<()> {
    ctx.log().info("nightly_cleanup running");
    // Idle in this example — a real app would purge stale data,
    // re-index, expire sessions, etc.
    Ok(())
}
