//! Mutations — read + write handlers.

use std::time::Duration;

use convex_native::{
    convex,
    prelude::*,
    MutationCtx,
    Rt,
};

use crate::schema::{
    Message,
    Profile,
    Tier,
    User,
};

/// Create a new user. Schedules a follow-up `send_welcome` action
/// to fire in a minute — the mutation's scheduler inherits the
/// enclosing request's `ExecutionContext`, so the scheduled job's
/// request-id chains off this call.
#[convex::mutation]
pub async fn create_user(
    ctx: &mut MutationCtx<'_, Rt>,
    email: String,
    display_name: String,
) -> anyhow::Result<Id<User>> {
    let now = ctx.unix_timestamp().as_secs_f64();
    let id = ctx
        .db()
        .insert(User {
            email,
            profile: Profile {
                tier: Tier::Free,
                display_name,
            },
            avatar_url: None,
            created_at: now,
        })
        .await?;

    ctx.scheduler()
        .run_action_after(
            Duration::from_secs(60),
            crate::actions::SendWelcome,
            crate::actions::SendWelcomeArgs { user_id: id },
        )
        .await?;

    Ok(id)
}

/// Post a message from an existing user. Demonstrates typed
/// `.try_get` (errors if the referenced user doesn't exist).
#[convex::mutation]
pub async fn send_message(
    ctx: &mut MutationCtx<'_, Rt>,
    author: Id<User>,
    body: String,
) -> anyhow::Result<Id<Message>> {
    let _: User = ctx.db().try_get(author).await?;
    let now = ctx.unix_timestamp().as_secs_f64();
    ctx.db()
        .insert(Message {
            author,
            body,
            created_at: now,
        })
        .await
}

/// Promote a user to Pro tier — demonstrates `patch(id, Patch { ... })`
/// on a field inside a nested struct. `UserPatch` is generated by
/// `#[derive(ConvexDocument)]` with every field wrapped in
/// `Option`; only fields set to `Some(..)` are written.
#[convex::mutation]
pub async fn promote(
    ctx: &mut MutationCtx<'_, Rt>,
    user: Id<User>,
    tier: Tier,
) -> anyhow::Result<()> {
    let existing = ctx.db().try_get(user).await?;
    // Mutate the nested struct, then replace — `patch` on nested
    // fields requires a full-document replace since `Patch` only
    // knows about top-level fields.
    let updated = User {
        profile: Profile {
            tier,
            display_name: existing.profile.display_name,
        },
        ..existing
    };
    ctx.db().replace(user, updated).await?;
    Ok(())
}
